// GENERATED by scripts/sync-registry.ts — do not edit.
// Vendored from templates/vite-react-ts (60 components).

export interface VariantAxis {
  prop: string
  options: string[]
  default: string | null
}

export interface ComponentEntry {
  name: string
  file: string
  importPath: string
  slots: string[]
  variants: VariantAxis[]
  props: string[]
  stateful: boolean
  deps: string[]
  exports: string[]
}

export const SHADCN: Record<string, ComponentEntry> = {
  "Accordion": {
    "name": "Accordion",
    "file": "accordion.tsx",
    "importPath": "@/components/ui/accordion",
    "slots": [
      "accordion",
      "accordion-content",
      "accordion-item",
      "accordion-trigger",
      "accordion-trigger-icon"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Accordion",
      "AccordionContent",
      "AccordionItem",
      "AccordionTrigger"
    ]
  },
  "AlertDialog": {
    "name": "AlertDialog",
    "file": "alert-dialog.tsx",
    "importPath": "@/components/ui/alert-dialog",
    "slots": [
      "alert-dialog",
      "alert-dialog-action",
      "alert-dialog-cancel",
      "alert-dialog-content",
      "alert-dialog-description",
      "alert-dialog-footer",
      "alert-dialog-header",
      "alert-dialog-media",
      "alert-dialog-overlay",
      "alert-dialog-portal",
      "alert-dialog-title",
      "alert-dialog-trigger"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "AlertDialog",
      "AlertDialogAction",
      "AlertDialogCancel",
      "AlertDialogContent",
      "AlertDialogDescription",
      "AlertDialogFooter",
      "AlertDialogHeader",
      "AlertDialogMedia",
      "AlertDialogOverlay",
      "AlertDialogPortal",
      "AlertDialogTitle",
      "AlertDialogTrigger"
    ]
  },
  "Alert": {
    "name": "Alert",
    "file": "alert.tsx",
    "importPath": "@/components/ui/alert",
    "slots": [
      "alert",
      "alert-action",
      "alert-description",
      "alert-title"
    ],
    "variants": [
      {
        "prop": "variant",
        "options": [
          "default",
          "destructive"
        ],
        "default": "default"
      }
    ],
    "props": [
      "className",
      "props",
      "variant"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "react"
    ],
    "exports": [
      "Alert",
      "AlertAction",
      "AlertDescription",
      "AlertTitle"
    ]
  },
  "AspectRatio": {
    "name": "AspectRatio",
    "file": "aspect-ratio.tsx",
    "importPath": "@/components/ui/aspect-ratio",
    "slots": [
      "aspect-ratio"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "radix-ui"
    ],
    "exports": [
      "AspectRatio"
    ]
  },
  "Attachment": {
    "name": "Attachment",
    "file": "attachment.tsx",
    "importPath": "@/components/ui/attachment",
    "slots": [
      "attachment",
      "attachment-action",
      "attachment-actions",
      "attachment-content",
      "attachment-description",
      "attachment-group",
      "attachment-media",
      "attachment-title",
      "attachment-trigger"
    ],
    "variants": [
      {
        "prop": "size",
        "options": [
          "default",
          "sm",
          "xs"
        ],
        "default": null
      },
      {
        "prop": "orientation",
        "options": [
          "horizontal",
          "vertical"
        ],
        "default": null
      },
      {
        "prop": "variant",
        "options": [
          "icon",
          "image"
        ],
        "default": "icon"
      },
      {
        "prop": "state",
        "options": [
          "idle",
          "uploading",
          "processing",
          "error",
          "done"
        ],
        "default": "done"
      }
    ],
    "props": [
      "className",
      "orientation",
      "props",
      "size",
      "state"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Attachment",
      "AttachmentAction",
      "AttachmentActions",
      "AttachmentContent",
      "AttachmentDescription",
      "AttachmentGroup",
      "AttachmentMedia",
      "AttachmentTitle",
      "AttachmentTrigger"
    ]
  },
  "Avatar": {
    "name": "Avatar",
    "file": "avatar.tsx",
    "importPath": "@/components/ui/avatar",
    "slots": [
      "avatar",
      "avatar-badge",
      "avatar-fallback",
      "avatar-group",
      "avatar-group-count",
      "avatar-image"
    ],
    "variants": [
      {
        "prop": "size",
        "options": [
          "default",
          "sm",
          "lg"
        ],
        "default": "default"
      }
    ],
    "props": [
      "className",
      "props",
      "size"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Avatar",
      "AvatarBadge",
      "AvatarFallback",
      "AvatarGroup",
      "AvatarGroupCount",
      "AvatarImage"
    ]
  },
  "Badge": {
    "name": "Badge",
    "file": "badge.tsx",
    "importPath": "@/components/ui/badge",
    "slots": [
      "badge"
    ],
    "variants": [
      {
        "prop": "variant",
        "options": [
          "default",
          "secondary",
          "destructive",
          "outline",
          "ghost",
          "link"
        ],
        "default": "default"
      }
    ],
    "props": [
      "asChild",
      "className",
      "props",
      "variant"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Badge",
      "badgeVariants"
    ]
  },
  "Breadcrumb": {
    "name": "Breadcrumb",
    "file": "breadcrumb.tsx",
    "importPath": "@/components/ui/breadcrumb",
    "slots": [
      "breadcrumb",
      "breadcrumb-ellipsis",
      "breadcrumb-item",
      "breadcrumb-link",
      "breadcrumb-list",
      "breadcrumb-page",
      "breadcrumb-separator"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Breadcrumb",
      "BreadcrumbEllipsis",
      "BreadcrumbItem",
      "BreadcrumbLink",
      "BreadcrumbList",
      "BreadcrumbPage",
      "BreadcrumbSeparator"
    ]
  },
  "Bubble": {
    "name": "Bubble",
    "file": "bubble.tsx",
    "importPath": "@/components/ui/bubble",
    "slots": [
      "bubble",
      "bubble-content",
      "bubble-group",
      "bubble-reactions"
    ],
    "variants": [
      {
        "prop": "variant",
        "options": [
          "default",
          "secondary",
          "muted",
          "tinted",
          "outline",
          "ghost",
          "destructive"
        ],
        "default": "default"
      },
      {
        "prop": "side",
        "options": [
          "top",
          "bottom"
        ],
        "default": "bottom"
      },
      {
        "prop": "align",
        "options": [
          "start",
          "end"
        ],
        "default": "end"
      }
    ],
    "props": [
      "align",
      "className",
      "props",
      "variant"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Bubble",
      "BubbleContent",
      "BubbleGroup",
      "BubbleReactions"
    ]
  },
  "ButtonGroup": {
    "name": "ButtonGroup",
    "file": "button-group.tsx",
    "importPath": "@/components/ui/button-group",
    "slots": [
      "button-group",
      "button-group-separator"
    ],
    "variants": [
      {
        "prop": "orientation",
        "options": [
          "horizontal",
          "vertical"
        ],
        "default": "horizontal"
      }
    ],
    "props": [
      "className",
      "orientation",
      "props"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "radix-ui"
    ],
    "exports": [
      "ButtonGroup",
      "ButtonGroupSeparator",
      "ButtonGroupText",
      "buttonGroupVariants"
    ]
  },
  "Button": {
    "name": "Button",
    "file": "button.tsx",
    "importPath": "@/components/ui/button",
    "slots": [
      "button"
    ],
    "variants": [
      {
        "prop": "variant",
        "options": [
          "default",
          "outline",
          "secondary",
          "ghost",
          "destructive",
          "link"
        ],
        "default": "default"
      },
      {
        "prop": "size",
        "options": [
          "default",
          "xs",
          "sm",
          "lg",
          "icon",
          "icon-xs",
          "icon-sm",
          "icon-lg"
        ],
        "default": "default"
      }
    ],
    "props": [
      "asChild",
      "className",
      "props",
      "size",
      "variant"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Button",
      "buttonVariants"
    ]
  },
  "Calendar": {
    "name": "Calendar",
    "file": "calendar.tsx",
    "importPath": "@/components/ui/calendar",
    "slots": [
      "calendar"
    ],
    "variants": [],
    "props": [
      "buttonVariant",
      "captionLayout",
      "className",
      "classNames",
      "components",
      "formatters",
      "locale",
      "props",
      "showOutsideDays"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "react",
      "react-day-picker"
    ],
    "exports": [
      "Calendar",
      "CalendarDayButton"
    ]
  },
  "Card": {
    "name": "Card",
    "file": "card.tsx",
    "importPath": "@/components/ui/card",
    "slots": [
      "card",
      "card-action",
      "card-content",
      "card-description",
      "card-footer",
      "card-header",
      "card-title"
    ],
    "variants": [
      {
        "prop": "size",
        "options": [
          "default",
          "sm"
        ],
        "default": "default"
      }
    ],
    "props": [
      "className",
      "props",
      "size"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "react"
    ],
    "exports": [
      "Card",
      "CardAction",
      "CardContent",
      "CardDescription",
      "CardFooter",
      "CardHeader",
      "CardTitle"
    ]
  },
  "Carousel": {
    "name": "Carousel",
    "file": "carousel.tsx",
    "importPath": "@/components/ui/carousel",
    "slots": [
      "carousel",
      "carousel-content",
      "carousel-item",
      "carousel-next",
      "carousel-previous"
    ],
    "variants": [],
    "props": [
      "children",
      "className",
      "opts",
      "orientation",
      "plugins",
      "props",
      "setApi"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "embla-carousel-react",
      "lucide-react",
      "react"
    ],
    "exports": [
      "Carousel",
      "CarouselApi",
      "CarouselContent",
      "CarouselItem",
      "CarouselNext",
      "CarouselPrevious",
      "useCarousel"
    ]
  },
  "ChartConfig": {
    "name": "ChartConfig",
    "file": "chart.tsx",
    "importPath": "@/components/ui/chart",
    "slots": [
      "chart"
    ],
    "variants": [],
    "props": [],
    "stateful": false,
    "deps": [
      "cn",
      "react",
      "recharts",
      "recharts"
    ],
    "exports": [
      "ChartConfig",
      "ChartContainer",
      "ChartLegend",
      "ChartLegendContent",
      "ChartStyle",
      "ChartTooltip",
      "ChartTooltipContent"
    ]
  },
  "Checkbox": {
    "name": "Checkbox",
    "file": "checkbox.tsx",
    "importPath": "@/components/ui/checkbox",
    "slots": [
      "checkbox",
      "checkbox-indicator"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": true,
    "deps": [
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Checkbox"
    ]
  },
  "Collapsible": {
    "name": "Collapsible",
    "file": "collapsible.tsx",
    "importPath": "@/components/ui/collapsible",
    "slots": [
      "collapsible",
      "collapsible-content",
      "collapsible-trigger"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "radix-ui"
    ],
    "exports": [
      "Collapsible",
      "CollapsibleContent",
      "CollapsibleTrigger"
    ]
  },
  "Combobox": {
    "name": "Combobox",
    "file": "combobox.tsx",
    "importPath": "@/components/ui/combobox",
    "slots": [
      "combobox-chip",
      "combobox-chip-input",
      "combobox-chip-remove",
      "combobox-chips",
      "combobox-clear",
      "combobox-collection",
      "combobox-content",
      "combobox-empty",
      "combobox-group",
      "combobox-item",
      "combobox-label",
      "combobox-list",
      "combobox-separator",
      "combobox-trigger",
      "combobox-value",
      "input-group-button"
    ],
    "variants": [],
    "props": [],
    "stateful": false,
    "deps": [
      "@base-ui/react",
      "cn",
      "lucide-react",
      "react"
    ],
    "exports": [
      "Combobox",
      "ComboboxChip",
      "ComboboxChips",
      "ComboboxChipsInput",
      "ComboboxCollection",
      "ComboboxContent",
      "ComboboxEmpty",
      "ComboboxGroup",
      "ComboboxInput",
      "ComboboxItem",
      "ComboboxLabel",
      "ComboboxList",
      "ComboboxSeparator",
      "ComboboxTrigger",
      "ComboboxValue",
      "useComboboxAnchor"
    ]
  },
  "Command": {
    "name": "Command",
    "file": "command.tsx",
    "importPath": "@/components/ui/command",
    "slots": [
      "command",
      "command-empty",
      "command-group",
      "command-input",
      "command-input-wrapper",
      "command-item",
      "command-list",
      "command-separator",
      "command-shortcut"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cmdk",
      "cn",
      "lucide-react",
      "react"
    ],
    "exports": [
      "Command",
      "CommandDialog",
      "CommandEmpty",
      "CommandGroup",
      "CommandInput",
      "CommandItem",
      "CommandList",
      "CommandSeparator",
      "CommandShortcut"
    ]
  },
  "ContextMenu": {
    "name": "ContextMenu",
    "file": "context-menu.tsx",
    "importPath": "@/components/ui/context-menu",
    "slots": [
      "context-menu",
      "context-menu-checkbox-item",
      "context-menu-content",
      "context-menu-group",
      "context-menu-item",
      "context-menu-label",
      "context-menu-portal",
      "context-menu-radio-group",
      "context-menu-radio-item",
      "context-menu-separator",
      "context-menu-shortcut",
      "context-menu-sub",
      "context-menu-sub-content",
      "context-menu-sub-trigger",
      "context-menu-trigger"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "ContextMenu",
      "ContextMenuCheckboxItem",
      "ContextMenuContent",
      "ContextMenuGroup",
      "ContextMenuItem",
      "ContextMenuLabel",
      "ContextMenuPortal",
      "ContextMenuRadioGroup",
      "ContextMenuRadioItem",
      "ContextMenuSeparator",
      "ContextMenuShortcut",
      "ContextMenuSub",
      "ContextMenuSubContent",
      "ContextMenuSubTrigger",
      "ContextMenuTrigger"
    ]
  },
  "Dialog": {
    "name": "Dialog",
    "file": "dialog.tsx",
    "importPath": "@/components/ui/dialog",
    "slots": [
      "dialog",
      "dialog-close",
      "dialog-content",
      "dialog-description",
      "dialog-footer",
      "dialog-header",
      "dialog-overlay",
      "dialog-portal",
      "dialog-title",
      "dialog-trigger"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Dialog",
      "DialogClose",
      "DialogContent",
      "DialogDescription",
      "DialogFooter",
      "DialogHeader",
      "DialogOverlay",
      "DialogPortal",
      "DialogTitle",
      "DialogTrigger"
    ]
  },
  "DirectionProvider": {
    "name": "DirectionProvider",
    "file": "direction.tsx",
    "importPath": "@/components/ui/direction",
    "slots": [],
    "variants": [],
    "props": [
      "children",
      "dir",
      "direction"
    ],
    "stateful": false,
    "deps": [
      "radix-ui",
      "react"
    ],
    "exports": [
      "DirectionProvider",
      "useDirection"
    ]
  },
  "Drawer": {
    "name": "Drawer",
    "file": "drawer.tsx",
    "importPath": "@/components/ui/drawer",
    "slots": [
      "drawer",
      "drawer-close",
      "drawer-content",
      "drawer-description",
      "drawer-footer",
      "drawer-header",
      "drawer-overlay",
      "drawer-portal",
      "drawer-title",
      "drawer-trigger"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "react",
      "vaul"
    ],
    "exports": [
      "Drawer",
      "DrawerClose",
      "DrawerContent",
      "DrawerDescription",
      "DrawerFooter",
      "DrawerHeader",
      "DrawerOverlay",
      "DrawerPortal",
      "DrawerTitle",
      "DrawerTrigger"
    ]
  },
  "DropdownMenu": {
    "name": "DropdownMenu",
    "file": "dropdown-menu.tsx",
    "importPath": "@/components/ui/dropdown-menu",
    "slots": [
      "dropdown-menu",
      "dropdown-menu-checkbox-item",
      "dropdown-menu-checkbox-item-indicator",
      "dropdown-menu-content",
      "dropdown-menu-group",
      "dropdown-menu-item",
      "dropdown-menu-label",
      "dropdown-menu-portal",
      "dropdown-menu-radio-group",
      "dropdown-menu-radio-item",
      "dropdown-menu-radio-item-indicator",
      "dropdown-menu-separator",
      "dropdown-menu-shortcut",
      "dropdown-menu-sub",
      "dropdown-menu-sub-content",
      "dropdown-menu-sub-trigger",
      "dropdown-menu-trigger"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "DropdownMenu",
      "DropdownMenuCheckboxItem",
      "DropdownMenuContent",
      "DropdownMenuGroup",
      "DropdownMenuItem",
      "DropdownMenuLabel",
      "DropdownMenuPortal",
      "DropdownMenuRadioGroup",
      "DropdownMenuRadioItem",
      "DropdownMenuSeparator",
      "DropdownMenuShortcut",
      "DropdownMenuSub",
      "DropdownMenuSubContent",
      "DropdownMenuSubTrigger",
      "DropdownMenuTrigger"
    ]
  },
  "Empty": {
    "name": "Empty",
    "file": "empty.tsx",
    "importPath": "@/components/ui/empty",
    "slots": [
      "empty",
      "empty-content",
      "empty-description",
      "empty-header",
      "empty-icon",
      "empty-title"
    ],
    "variants": [
      {
        "prop": "variant",
        "options": [
          "default",
          "icon"
        ],
        "default": "default"
      }
    ],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn"
    ],
    "exports": [
      "Empty",
      "EmptyContent",
      "EmptyDescription",
      "EmptyHeader",
      "EmptyMedia",
      "EmptyTitle"
    ]
  },
  "Field": {
    "name": "Field",
    "file": "field.tsx",
    "importPath": "@/components/ui/field",
    "slots": [
      "field",
      "field-content",
      "field-description",
      "field-error",
      "field-group",
      "field-label",
      "field-legend",
      "field-separator",
      "field-separator-content",
      "field-set"
    ],
    "variants": [
      {
        "prop": "orientation",
        "options": [
          "vertical",
          "horizontal",
          "responsive"
        ],
        "default": "vertical"
      }
    ],
    "props": [
      "className",
      "orientation",
      "props"
    ],
    "stateful": true,
    "deps": [
      "class-variance-authority",
      "cn",
      "react"
    ],
    "exports": [
      "Field",
      "FieldContent",
      "FieldDescription",
      "FieldError",
      "FieldGroup",
      "FieldLabel",
      "FieldLegend",
      "FieldSeparator",
      "FieldSet",
      "FieldTitle"
    ]
  },
  "HoverCard": {
    "name": "HoverCard",
    "file": "hover-card.tsx",
    "importPath": "@/components/ui/hover-card",
    "slots": [
      "hover-card",
      "hover-card-content",
      "hover-card-portal",
      "hover-card-trigger"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "HoverCard",
      "HoverCardContent",
      "HoverCardTrigger"
    ]
  },
  "InputGroup": {
    "name": "InputGroup",
    "file": "input-group.tsx",
    "importPath": "@/components/ui/input-group",
    "slots": [
      "input-group",
      "input-group-addon",
      "input-group-control"
    ],
    "variants": [
      {
        "prop": "align",
        "options": [
          "inline-start",
          "inline-end",
          "block-start",
          "block-end"
        ],
        "default": "inline-start"
      },
      {
        "prop": "size",
        "options": [
          "xs",
          "sm",
          "icon-xs",
          "icon-sm"
        ],
        "default": "xs"
      }
    ],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "react"
    ],
    "exports": [
      "InputGroup",
      "InputGroupAddon",
      "InputGroupButton",
      "InputGroupInput",
      "InputGroupText",
      "InputGroupTextarea"
    ]
  },
  "InputOTP": {
    "name": "InputOTP",
    "file": "input-otp.tsx",
    "importPath": "@/components/ui/input-otp",
    "slots": [
      "input-otp",
      "input-otp-group",
      "input-otp-separator",
      "input-otp-slot"
    ],
    "variants": [],
    "props": [
      "className",
      "containerClassName",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "input-otp",
      "lucide-react",
      "react"
    ],
    "exports": [
      "InputOTP",
      "InputOTPGroup",
      "InputOTPSeparator",
      "InputOTPSlot"
    ]
  },
  "Input": {
    "name": "Input",
    "file": "input.tsx",
    "importPath": "@/components/ui/input",
    "slots": [
      "input"
    ],
    "variants": [],
    "props": [
      "className",
      "props",
      "type"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "react"
    ],
    "exports": [
      "Input"
    ]
  },
  "Item": {
    "name": "Item",
    "file": "item.tsx",
    "importPath": "@/components/ui/item",
    "slots": [
      "item",
      "item-actions",
      "item-content",
      "item-description",
      "item-footer",
      "item-group",
      "item-header",
      "item-media",
      "item-separator",
      "item-title"
    ],
    "variants": [
      {
        "prop": "variant",
        "options": [
          "default",
          "outline",
          "muted"
        ],
        "default": "default"
      },
      {
        "prop": "size",
        "options": [
          "default",
          "sm",
          "xs"
        ],
        "default": "default"
      },
      {
        "prop": "variant",
        "options": [
          "default",
          "icon",
          "image"
        ],
        "default": null
      }
    ],
    "props": [
      "asChild",
      "className",
      "props",
      "size",
      "variant"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Item",
      "ItemActions",
      "ItemContent",
      "ItemDescription",
      "ItemFooter",
      "ItemGroup",
      "ItemHeader",
      "ItemMedia",
      "ItemSeparator",
      "ItemTitle"
    ]
  },
  "Kbd": {
    "name": "Kbd",
    "file": "kbd.tsx",
    "importPath": "@/components/ui/kbd",
    "slots": [
      "kbd",
      "kbd-group"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn"
    ],
    "exports": [
      "Kbd",
      "KbdGroup"
    ]
  },
  "Label": {
    "name": "Label",
    "file": "label.tsx",
    "importPath": "@/components/ui/label",
    "slots": [
      "label"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Label"
    ]
  },
  "Marker": {
    "name": "Marker",
    "file": "marker.tsx",
    "importPath": "@/components/ui/marker",
    "slots": [
      "marker",
      "marker-content",
      "marker-icon"
    ],
    "variants": [
      {
        "prop": "variant",
        "options": [
          "default",
          "separator",
          "border"
        ],
        "default": null
      }
    ],
    "props": [
      "asChild",
      "className",
      "props",
      "variant"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Marker",
      "MarkerContent",
      "MarkerIcon",
      "markerVariants"
    ]
  },
  "Menubar": {
    "name": "Menubar",
    "file": "menubar.tsx",
    "importPath": "@/components/ui/menubar",
    "slots": [
      "menubar",
      "menubar-checkbox-item",
      "menubar-content",
      "menubar-group",
      "menubar-item",
      "menubar-label",
      "menubar-menu",
      "menubar-portal",
      "menubar-radio-group",
      "menubar-radio-item",
      "menubar-separator",
      "menubar-shortcut",
      "menubar-sub",
      "menubar-sub-content",
      "menubar-sub-trigger",
      "menubar-trigger"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Menubar",
      "MenubarCheckboxItem",
      "MenubarContent",
      "MenubarGroup",
      "MenubarItem",
      "MenubarLabel",
      "MenubarMenu",
      "MenubarPortal",
      "MenubarRadioGroup",
      "MenubarRadioItem",
      "MenubarSeparator",
      "MenubarShortcut",
      "MenubarSub",
      "MenubarSubContent",
      "MenubarSubTrigger",
      "MenubarTrigger"
    ]
  },
  "MessageScroller": {
    "name": "MessageScroller",
    "file": "message-scroller.tsx",
    "importPath": "@/components/ui/message-scroller",
    "slots": [
      "message-scroller",
      "message-scroller-button",
      "message-scroller-content",
      "message-scroller-item",
      "message-scroller-viewport"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "@shadcn/react/message-scroller",
      "cn",
      "lucide-react",
      "react"
    ],
    "exports": [
      "MessageScroller",
      "MessageScrollerButton",
      "MessageScrollerContent",
      "MessageScrollerItem",
      "MessageScrollerProvider",
      "MessageScrollerViewport",
      "useMessageScroller",
      "useMessageScrollerScrollable",
      "useMessageScrollerVisibility"
    ]
  },
  "Message": {
    "name": "Message",
    "file": "message.tsx",
    "importPath": "@/components/ui/message",
    "slots": [
      "message",
      "message-avatar",
      "message-content",
      "message-footer",
      "message-group",
      "message-header"
    ],
    "variants": [
      {
        "prop": "align",
        "options": [
          "start",
          "end"
        ],
        "default": "start"
      }
    ],
    "props": [
      "align",
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "react"
    ],
    "exports": [
      "Message",
      "MessageAvatar",
      "MessageContent",
      "MessageFooter",
      "MessageGroup",
      "MessageHeader"
    ]
  },
  "NativeSelect": {
    "name": "NativeSelect",
    "file": "native-select.tsx",
    "importPath": "@/components/ui/native-select",
    "slots": [
      "native-select",
      "native-select-icon",
      "native-select-optgroup",
      "native-select-option",
      "native-select-wrapper"
    ],
    "variants": [],
    "props": [
      "className",
      "props",
      "size"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "react"
    ],
    "exports": [
      "NativeSelect",
      "NativeSelectOptGroup",
      "NativeSelectOption"
    ]
  },
  "NavigationMenu": {
    "name": "NavigationMenu",
    "file": "navigation-menu.tsx",
    "importPath": "@/components/ui/navigation-menu",
    "slots": [
      "navigation-menu",
      "navigation-menu-content",
      "navigation-menu-indicator",
      "navigation-menu-item",
      "navigation-menu-link",
      "navigation-menu-list",
      "navigation-menu-trigger",
      "navigation-menu-viewport"
    ],
    "variants": [],
    "props": [
      "children",
      "className",
      "props",
      "viewport"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "NavigationMenu",
      "NavigationMenuContent",
      "NavigationMenuIndicator",
      "NavigationMenuItem",
      "NavigationMenuLink",
      "NavigationMenuList",
      "NavigationMenuTrigger",
      "NavigationMenuViewport",
      "navigationMenuTriggerStyle"
    ]
  },
  "Pagination": {
    "name": "Pagination",
    "file": "pagination.tsx",
    "importPath": "@/components/ui/pagination",
    "slots": [
      "pagination",
      "pagination-content",
      "pagination-ellipsis",
      "pagination-item",
      "pagination-link"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "react"
    ],
    "exports": [
      "Pagination",
      "PaginationContent",
      "PaginationEllipsis",
      "PaginationItem",
      "PaginationLink",
      "PaginationNext",
      "PaginationPrevious"
    ]
  },
  "Popover": {
    "name": "Popover",
    "file": "popover.tsx",
    "importPath": "@/components/ui/popover",
    "slots": [
      "popover",
      "popover-anchor",
      "popover-content",
      "popover-description",
      "popover-header",
      "popover-title",
      "popover-trigger"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Popover",
      "PopoverAnchor",
      "PopoverContent",
      "PopoverDescription",
      "PopoverHeader",
      "PopoverTitle",
      "PopoverTrigger"
    ]
  },
  "Progress": {
    "name": "Progress",
    "file": "progress.tsx",
    "importPath": "@/components/ui/progress",
    "slots": [
      "progress",
      "progress-indicator"
    ],
    "variants": [],
    "props": [
      "className",
      "props",
      "value"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Progress"
    ]
  },
  "RadioGroup": {
    "name": "RadioGroup",
    "file": "radio-group.tsx",
    "importPath": "@/components/ui/radio-group",
    "slots": [
      "radio-group",
      "radio-group-indicator",
      "radio-group-item"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": true,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "RadioGroup",
      "RadioGroupItem"
    ]
  },
  "ResizableHandle": {
    "name": "ResizableHandle",
    "file": "resizable.tsx",
    "importPath": "@/components/ui/resizable",
    "slots": [
      "resizable-handle",
      "resizable-panel",
      "resizable-panel-group"
    ],
    "variants": [],
    "props": [
      "className",
      "props",
      "withHandle"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "react-resizable-panels"
    ],
    "exports": [
      "ResizableHandle",
      "ResizablePanel",
      "ResizablePanelGroup"
    ]
  },
  "ScrollArea": {
    "name": "ScrollArea",
    "file": "scroll-area.tsx",
    "importPath": "@/components/ui/scroll-area",
    "slots": [
      "scroll-area",
      "scroll-area-scrollbar",
      "scroll-area-thumb",
      "scroll-area-viewport"
    ],
    "variants": [],
    "props": [
      "children",
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "ScrollArea",
      "ScrollBar"
    ]
  },
  "Select": {
    "name": "Select",
    "file": "select.tsx",
    "importPath": "@/components/ui/select",
    "slots": [
      "select",
      "select-content",
      "select-group",
      "select-item",
      "select-label",
      "select-scroll-down-button",
      "select-scroll-up-button",
      "select-separator",
      "select-trigger",
      "select-value"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Select",
      "SelectContent",
      "SelectGroup",
      "SelectItem",
      "SelectLabel",
      "SelectScrollDownButton",
      "SelectScrollUpButton",
      "SelectSeparator",
      "SelectTrigger",
      "SelectValue"
    ]
  },
  "Separator": {
    "name": "Separator",
    "file": "separator.tsx",
    "importPath": "@/components/ui/separator",
    "slots": [
      "separator"
    ],
    "variants": [],
    "props": [
      "className",
      "decorative",
      "orientation",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Separator"
    ]
  },
  "Sheet": {
    "name": "Sheet",
    "file": "sheet.tsx",
    "importPath": "@/components/ui/sheet",
    "slots": [
      "sheet",
      "sheet-close",
      "sheet-content",
      "sheet-description",
      "sheet-footer",
      "sheet-header",
      "sheet-overlay",
      "sheet-portal",
      "sheet-title",
      "sheet-trigger"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Sheet",
      "SheetClose",
      "SheetContent",
      "SheetDescription",
      "SheetFooter",
      "SheetHeader",
      "SheetTitle",
      "SheetTrigger"
    ]
  },
  "Sidebar": {
    "name": "Sidebar",
    "file": "sidebar.tsx",
    "importPath": "@/components/ui/sidebar",
    "slots": [
      "sidebar",
      "sidebar-container",
      "sidebar-content",
      "sidebar-footer",
      "sidebar-gap",
      "sidebar-group",
      "sidebar-group-action",
      "sidebar-group-content",
      "sidebar-group-label",
      "sidebar-header",
      "sidebar-inner",
      "sidebar-input",
      "sidebar-inset",
      "sidebar-menu",
      "sidebar-menu-action",
      "sidebar-menu-badge",
      "sidebar-menu-button",
      "sidebar-menu-item",
      "sidebar-menu-skeleton",
      "sidebar-menu-sub",
      "sidebar-menu-sub-button",
      "sidebar-menu-sub-item",
      "sidebar-rail",
      "sidebar-separator",
      "sidebar-trigger",
      "sidebar-wrapper"
    ],
    "variants": [
      {
        "prop": "variant",
        "options": [
          "default",
          "outline"
        ],
        "default": "default"
      },
      {
        "prop": "size",
        "options": [
          "default",
          "sm",
          "lg"
        ],
        "default": "default"
      },
      {
        "prop": "side",
        "options": [
          "left",
          "right"
        ],
        "default": "left"
      },
      {
        "prop": "collapsible",
        "options": [
          "offcanvas",
          "icon",
          "none"
        ],
        "default": "offcanvas"
      }
    ],
    "props": [
      "children",
      "className",
      "collapsible",
      "dir",
      "props",
      "side",
      "variant"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "lucide-react",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Sidebar",
      "SidebarContent",
      "SidebarFooter",
      "SidebarGroup",
      "SidebarGroupAction",
      "SidebarGroupContent",
      "SidebarGroupLabel",
      "SidebarHeader",
      "SidebarInput",
      "SidebarInset",
      "SidebarMenu",
      "SidebarMenuAction",
      "SidebarMenuBadge",
      "SidebarMenuButton",
      "SidebarMenuItem",
      "SidebarMenuSkeleton",
      "SidebarMenuSub",
      "SidebarMenuSubButton",
      "SidebarMenuSubItem",
      "SidebarProvider",
      "SidebarRail",
      "SidebarSeparator",
      "SidebarTrigger",
      "useSidebar"
    ]
  },
  "Skeleton": {
    "name": "Skeleton",
    "file": "skeleton.tsx",
    "importPath": "@/components/ui/skeleton",
    "slots": [
      "skeleton"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn"
    ],
    "exports": [
      "Skeleton"
    ]
  },
  "Slider": {
    "name": "Slider",
    "file": "slider.tsx",
    "importPath": "@/components/ui/slider",
    "slots": [
      "slider",
      "slider-range",
      "slider-thumb",
      "slider-track"
    ],
    "variants": [],
    "props": [
      "className",
      "defaultValue",
      "max",
      "min",
      "props",
      "value"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Slider"
    ]
  },
  "Toaster": {
    "name": "Toaster",
    "file": "sonner.tsx",
    "importPath": "@/components/ui/sonner",
    "slots": [],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "lucide-react",
      "next-themes",
      "sonner"
    ],
    "exports": [
      "Toaster"
    ]
  },
  "Spinner": {
    "name": "Spinner",
    "file": "spinner.tsx",
    "importPath": "@/components/ui/spinner",
    "slots": [
      "spinner"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "lucide-react"
    ],
    "exports": [
      "Spinner"
    ]
  },
  "Switch": {
    "name": "Switch",
    "file": "switch.tsx",
    "importPath": "@/components/ui/switch",
    "slots": [
      "switch",
      "switch-thumb"
    ],
    "variants": [
      {
        "prop": "size",
        "options": [
          "sm",
          "default"
        ],
        "default": "default"
      }
    ],
    "props": [
      "className",
      "props",
      "size"
    ],
    "stateful": true,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Switch"
    ]
  },
  "Table": {
    "name": "Table",
    "file": "table.tsx",
    "importPath": "@/components/ui/table",
    "slots": [
      "table",
      "table-body",
      "table-caption",
      "table-cell",
      "table-container",
      "table-footer",
      "table-head",
      "table-header",
      "table-row"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "react"
    ],
    "exports": [
      "Table",
      "TableBody",
      "TableCaption",
      "TableCell",
      "TableFooter",
      "TableHead",
      "TableHeader",
      "TableRow"
    ]
  },
  "Tabs": {
    "name": "Tabs",
    "file": "tabs.tsx",
    "importPath": "@/components/ui/tabs",
    "slots": [
      "tabs",
      "tabs-content",
      "tabs-list",
      "tabs-trigger"
    ],
    "variants": [
      {
        "prop": "variant",
        "options": [
          "default",
          "line"
        ],
        "default": "default"
      }
    ],
    "props": [
      "className",
      "orientation",
      "props"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Tabs",
      "TabsContent",
      "TabsList",
      "TabsTrigger",
      "tabsListVariants"
    ]
  },
  "Textarea": {
    "name": "Textarea",
    "file": "textarea.tsx",
    "importPath": "@/components/ui/textarea",
    "slots": [
      "textarea"
    ],
    "variants": [],
    "props": [
      "className",
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "react"
    ],
    "exports": [
      "Textarea"
    ]
  },
  "ToggleGroup": {
    "name": "ToggleGroup",
    "file": "toggle-group.tsx",
    "importPath": "@/components/ui/toggle-group",
    "slots": [
      "toggle-group",
      "toggle-group-item"
    ],
    "variants": [
      {
        "prop": "orientation",
        "options": [
          "horizontal",
          "vertical"
        ],
        "default": "horizontal"
      }
    ],
    "props": [
      "children",
      "className",
      "orientation",
      "props",
      "size",
      "spacing",
      "variant"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "ToggleGroup",
      "ToggleGroupItem"
    ]
  },
  "Toggle": {
    "name": "Toggle",
    "file": "toggle.tsx",
    "importPath": "@/components/ui/toggle",
    "slots": [
      "toggle"
    ],
    "variants": [
      {
        "prop": "variant",
        "options": [
          "default",
          "outline"
        ],
        "default": "default"
      },
      {
        "prop": "size",
        "options": [
          "default",
          "sm",
          "lg"
        ],
        "default": "default"
      }
    ],
    "props": [
      "className",
      "props",
      "size",
      "variant"
    ],
    "stateful": false,
    "deps": [
      "class-variance-authority",
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Toggle",
      "toggleVariants"
    ]
  },
  "Tooltip": {
    "name": "Tooltip",
    "file": "tooltip.tsx",
    "importPath": "@/components/ui/tooltip",
    "slots": [
      "tooltip",
      "tooltip-content",
      "tooltip-provider",
      "tooltip-trigger"
    ],
    "variants": [],
    "props": [
      "props"
    ],
    "stateful": false,
    "deps": [
      "cn",
      "radix-ui",
      "react"
    ],
    "exports": [
      "Tooltip",
      "TooltipContent",
      "TooltipProvider",
      "TooltipTrigger"
    ]
  }
}
