/**
 * Generate src/registry/lucide/index.generated.ts.
 *
 *   npm run sync-lucide
 *
 * The registry is built from `lucide-react`, the package the generated project
 * actually imports. Building it from a different Lucide package produced 281
 * names this version does not export, which would have emitted imports that
 * fail to compile. Render each icon to static markup and read the geometry and
 * the `lucide-<kebab>` class React writes for it.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import * as lucideReact from 'lucide-react'
import { features, hashShape } from '../src/icons/normalize.ts'
import type { IconChild } from '../src/types.ts'

const ROOT = new URL('..', import.meta.url)
const OUT = new URL('src/registry/lucide/index.generated.ts', ROOT)

const named = Object.keys(lucideReact).filter((n) => /^[A-Z]/.test(n))

/** Minimal SVG reader: enough for Lucide's output, which is always flat. */
function parseSvg(markup: string): { className: string; children: IconChild[] } | null {
  if (!markup.startsWith('<svg')) return null
  const open = /^<svg\b([^>]*)>/.exec(markup)
  if (!open) return null

  const attrsOf = (s: string): Record<string, string> => {
    const out: Record<string, string> = {}
    for (const m of s.matchAll(/([\w:-]+)="([^"]*)"/g)) out[m[1]] = m[2]
    return out
  }

  const className = attrsOf(open[1]).class ?? ''
  const children: IconChild[] = []
  for (const m of markup.matchAll(/<(?!\/)([a-z]+)\b([^>]*?)\/?>/g)) {
    if (m[1] === 'svg') continue
    children.push([m[1], attrsOf(m[2])])
  }
  return { className, children }
}

/** Lucide's filename convention, digits included: ArrowDown01 -> arrow-down-0-1. */
function kebabify(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-zA-Z])(\d)/g, '$1-$2')
    .replace(/(\d)([a-zA-Z])/g, '$1-$2')
    .toLowerCase()
}

interface Rendered {
  name: string
  /** Filename stem, from the `lucide-<stem>` class React renders. */
  stem: string
  children: IconChild[]
}

const rendered: Rendered[] = []
const skipped: string[] = []

for (const name of named) {
  let markup: string
  try {
    markup = renderToStaticMarkup(createElement(lucideReact[name] as never))
  } catch {
    // `icons`, `createLucideIcon` and similar helpers throw when rendered.
    skipped.push(name)
    continue
  }

  const parsed = parseSvg(markup)
  if (!parsed) {
    skipped.push(name)
    continue
  }

  const stem = /(?:^|\s)lucide-([\w-]+)(?:\s|$)/.exec(parsed.className)?.[1] ?? ''
  rendered.push({ name, stem, children: parsed.children })
}

// The stem is the filename, so the canonical spelling is the export that
// kebabifies to it: TriangleAlert -> triangle-alert. Picking by sort order
// instead would crown AlertTriangle, which this version still exports only as a
// deprecated alias.
const canonicalByStem = new Map<string, string>()
for (const r of rendered) {
  if (!r.stem) continue
  const existing = canonicalByStem.get(r.stem)
  if (!existing) {
    canonicalByStem.set(r.stem, r.name)
    continue
  }
  if (kebabify(r.name) === r.stem && kebabify(existing) !== r.stem) {
    canonicalByStem.set(r.stem, r.name)
  }
}

const names: string[] = []
const canonicalOf: Record<string, string> = {}
const hashMap: Record<string, string> = {}
const featureMap: Record<string, ReturnType<typeof features>> = {}

for (const r of rendered) {
  names.push(r.name)
  const canonical = canonicalByStem.get(r.stem) ?? r.name
  if (canonical !== r.name) canonicalOf[r.name] = canonical

  // Keyed by canonical, so an alias never shadows the real spelling.
  hashMap[hashShape(r.children)] ??= canonical
  featureMap[canonical] = features(r.children)
}

names.sort()

const version = JSON.parse(
  await readFile(new URL('node_modules/lucide-react/package.json', ROOT), 'utf8'),
).version as string

const body = `// GENERATED by scripts/sync-lucide.ts — do not edit.
// lucide-react ${version}
import type { IconFeatures } from '../../icons/normalize.ts'

/** Every name this Lucide version exports. Emitting anything else breaks the build. */
export const LUCIDE_NAMES = [
${names.map((n) => `  '${n}',`).join('\n')}
] as const

export type LucideName = (typeof LUCIDE_NAMES)[number]

/**
 * Current name for deprecated spellings this version still exports
 * (AlertTriangle -> TriangleAlert). Derived from Lucide's own filenames.
 */
export const LUCIDE_ALIASES: Record<string, string> = ${JSON.stringify(canonicalOf, null, 2)}

/** Shape hash -> canonical icon name. Exact SVG match, no vision needed. */
export const LUCIDE_BY_HASH: Record<string, string> = ${JSON.stringify(hashMap, null, 2)}

/** Coarse fingerprints, keyed by canonical name. Used only to rank fuzzy candidates. */
export const LUCIDE_FEATURES: Record<string, IconFeatures> = ${JSON.stringify(featureMap)}
`

await mkdir(new URL('src/registry/lucide/', ROOT), { recursive: true })
await writeFile(OUT, body)

console.log(`${names.length} icons from lucide-react ${version}, ${Object.keys(hashMap).length} hashes`)
if (skipped.length) console.log(`skipped (non-icon exports): ${skipped.join(', ')}`)
